### ISSUE TITLE
submitting form leaving a blank value will display an error

### ISSUE THREAD

**Issue by Matthieu-ui** [IsaacJrTypes/p2-branch-pull-merge-repeat#7]
Unsupported operand types: string - int

**Comment by IsaacJrTypes** [comment]
fixed issue, problem was that isset registers empty string as true. Use empty() for empty strings to return false. 

Overall, I really liked the way you separated error handling for readability

**Comment by Matthieu-ui** [comment]
Awesome nice!! I see! I did that originally on my project and didn't have the issue. thank you!
